# Generated by Django 4.1 on 2023-05-14 08:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("wagtailcore", "0083_workflowcontenttype"),
        ("pages", "0005_homeindexpage_require_registration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("benefit", wagtail.fields.RichTextField()),
                ("method_input", wagtail.fields.RichTextField()),
                ("method_output", wagtail.fields.RichTextField()),
                ("why", wagtail.fields.RichTextField()),
                ("how", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name": "method",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="MethodPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_methods",
                        to="pages.methodpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="methodpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="pages.MethodPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
