# Generated by Django 4.2.1 on 2023-05-15 08:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_methodpage_methodpagetag_methodpage_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="methodpage",
            name="how",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
