# Generated by Django 4.2.7 on 2023-12-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_alter_methodpage_how"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeindexpage",
            options={"verbose_name": "Index Page"},
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="frontpage",
            field=models.BooleanField(default=False),
        ),
    ]
