# Generated by Django 4.2.7 on 2024-01-20 07:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_homepage_search_image_methodpage_search_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="card_subtitle",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="card_title",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
