# Generated by Django 4.2.7 on 2024-01-21 07:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index
import wagtailmetadata.models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("pages", "0010_alter_homeindexpage_options_homepage_card_subtitle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="search_image",
        ),
        migrations.RemoveField(
            model_name="methodpage",
            name="search_image",
        ),
        migrations.CreateModel(
            name="SEOPageMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_engine_index",
                    models.BooleanField(
                        default=True,
                        verbose_name="Allow search engines to index this page?",
                    ),
                ),
                (
                    "search_engine_changefreq",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("always", "Always"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("never", "Never"),
                        ],
                        help_text="How frequently the page is likely to change? (Leave blank for default)",
                        max_length=25,
                        null=True,
                        verbose_name="Search Engine Change Frequency (Optional)",
                    ),
                ),
                (
                    "search_engine_priority",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="The priority of this URL relative to other URLs on your site. Valid values range from 0.0 to 1.0. (Leave blank for default)",
                        max_digits=2,
                        null=True,
                        verbose_name="Search Engine Priority (Optional)",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Search image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.search.index.Indexed,
                wagtailmetadata.models.WagtailImageMetadataMixin,
                models.Model,
            ),
        ),
    ]
